# VM
- :name:
    vm-tools-centos
  :short_name:
    vm:centos
  :role:
    vm_base

- :name:
    vm-tools-ubuntu
  :short_name:
    vm:ubuntu
  :role:
    vm_base

- :name:
    isucon6-qualify
  :short_name:
    isucon6
  :role:
    vm_base
